### ISSUE TITLE
Listado de especies

### ISSUE THREAD

**Issue by calonso-conabio** [calonso-conabio/buscador#15]
Se tiene que dividir la pagina cuando te arroja resultados en dos "tabs"
Un "tab" donde te muestra los resultados de tus filtros
El otro "tab" donde te muestra el listado de especies del taxon que escogiste en la parte del autocompletado.

Esto implica mover en especies_controller/resultados la logica para saber que quiere ver,
asi como implemenetar una manera facil de acomodar los taxones en forma de listado de especies.

**Comment by calonso-conabio** [comment]
Pendiente, lo acomoda fortuitamente por ID

**Comment by albertoglezba** [comment]
se resolvio, ahora falta mejorarlo, para ello el issue https://github.com/calonso-conabio/buscador/issues/31
