### ISSUE TITLE
Quitar los taxones repetidos que no mostraremos

### ISSUE THREAD

**Issue by calonso-conabio** [calonso-conabio/buscador#16]
Exiten varias ramas en las cuales los taxones estan repetidos, siendo de diferentes bases, esto ocasiona que cuando autocompletas con redis o buscas ese taxon no sepas cual es el correcto ya que no es una cuestion de "sinonimia", una posible solucion es crear un campo nuevo en cada base de la tabla "Nombre" que por default sea "1", y marcar los taxones que no son los correctos con "0" y asi evitar desplegar los taxones repetidos incorrectos desde el query.

**Comment by albertoglezba** [comment]
otra es tener una tabla donde se tengan los id's q son repetidos y no tomarlos en cuenta con un mini join, con el fin de evitar redundancia de datos

**Comment by calonso-conabio** [comment]
Al final se solucionara cambiando directamente el campo ancestry_ascendente_directo y ancestry ascendente_obligartorio en la base.

**Comment by calonso-conabio** [comment]
Y se quitaron los reinos repetidos, quedando solo 5
