### ISSUE TITLE
imágenes no corresponden con la especie

### ISSUE THREAD

**Issue by dianhrcat** [calonso-conabio/buscador#311]
En http://colibri.conabio.gob.mx:4000/especies/131148-ophionereis-vittata se muestran las imágenes que corresponden a otra  especie (Isostichopus fuscus) 
y los nombres comunes que muestra en la pantalla de inicio de la especie (abajo del nombre científico, son: Ofiuro, Pepino de mar pardo Español; Brown Sea Cucumber Inglés;
es decir está mezclando nombres comunes. 

Isostichopus fuscus es un pepino de mar 
Ophionereis vittata es un ofiuro

**Comment by calonso-conabio** [comment]
Hola @dianhrcat ,

Es correcto las imagenes estan mal vinculadas, limpie el ID de naturaslista ya que las imagenes y los nombres comunes diferentes a catalogos vienen de allí,  esto paso porque el ID de naturalista estaba vinculado a un nombre científico que probablemente ya cambió en catálogos. 

Pero bueno correremos un proceso que autocomplete toda la información que es como debería funcionar. De moento solo limpie ese ID.
