### ISSUE TITLE
Error imágenes vinculadas al taxón y en el link con Naturalista

### ISSUE THREAD

**Issue by sfrontana** [calonso-conabio/buscador#313]
@calonso-conabio @albertoglezba Les comento que para equinodermos adicional a lo que ya les comentó Diana, se ha detectado que las imágenes vinculadas al taxón no corresponden con la especie en cuestión, así mismo cuando se da click en el recuadro naranja de la derecha con nombre **Mas información científica sobre  la especie** y se selecciona la opción _naturalista_ nos lleva al taxón de las imágenes que no corresponden con el taxón buscado desde enciclovida. Algunos ejemplos son:
http://colibri.conabio.gob.mx:4000/especies/130461-diadema-mexicanum
http://colibri.conabio.gob.mx:4000/especies/130558-oreaster-reticulatus
http://colibri.conabio.gob.mx:4000/especies/130615-ophiactis-savignyi
Quedo al pendiente de cualquier comentario de su parte, saludos Sarita Frontana.

**Comment by calonso-conabio** [comment]
Hola @sfrontana ,

Este comentario tiene la misma respuesta que le coemnte a Diana, 
limpie la tabla de momento pero es un proceso que se autocompletará automáticamente.


Saludos.
