### ISSUE TITLE
Error de administración de comentarios

### ISSUE THREAD

**Issue by AliciaResendiz** [calonso-conabio/buscador#322]
Hola, ya no tengo problemas al visualizar el administrador de comentarios, sin embargo, no me aparece ninguno (verifiqué filtros) y noté que tengo permisos para Fungi y Urochordata, pero debería ser Fungi, Chordata, Acanthocephala y Platyhelminthes, adjunto la imagen en su correo, saludos

**Comment by AliciaResendiz** [comment]
Alberto, ya puedo ver los permisos, aunque no se muestra ningún comentario...ni siquiera los que ya resolví 

----- Mensaje original -----

De: "Alberto González B." <notifications@github.com> 
Para: "calonso-conabio/buscador" <buscador@noreply.github.com> 
CC: "Alicia Reséndiz" <mresendiz@conabio.gob.mx>, "Author" <author@noreply.github.com> 
Enviados: Jueves, 30 de Agosto 2018 14:25:28 
Asunto: Re: [calonso-conabio/buscador] Error de administración de comentarios (#322) 



Podrías checar de nuevo, ya te agregue dicha taxonomía específica 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 



-- 
Biól. Martha Alicia Reséndiz López 
Especialista de Catálogos de Autoridades Taxonómicas 
martha.resendiz@conabio.gob.mx | Tel. 5004.4942 

Comisión Nacional para el Conocimiento 
y Uso de la Biodiversidad 
Liga Periférico - Insurgentes Sur, Núm. 4903, 
Col. Parques del Pedregal, Delegación Tlalpan, 
C.P. 14010, México, D.F. | Tel. 5004.5000 

www.conabio.gob.mx | www.biodiversidad.gob.mx 
Facebook | Twitter | YouTube

**Comment by albertoglezba** [comment]
ok, ya subimos otro parche, puedes intentar de nuevo?

**Comment by AliciaResendiz** [comment]
Listo, ya puedo visualizar todos los comentarios para los grupos correspondientes, gracias! 

----- Mensaje original -----

De: "Alberto González B." <notifications@github.com> 
Para: "calonso-conabio/buscador" <buscador@noreply.github.com> 
CC: "Alicia Reséndiz" <mresendiz@conabio.gob.mx>, "Author" <author@noreply.github.com> 
Enviados: Viernes, 31 de Agosto 2018 0:58:08 
Asunto: Re: [calonso-conabio/buscador] Error de administración de comentarios (#322) 



ok, ya subimos otro parche, puedes intentar de nuevo? 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or mute the thread . 



-- 
Biól. Martha Alicia Reséndiz López 
Especialista de Catálogos de Autoridades Taxonómicas 
martha.resendiz@conabio.gob.mx | Tel. 5004.4942 

Comisión Nacional para el Conocimiento 
y Uso de la Biodiversidad 
Liga Periférico - Insurgentes Sur, Núm. 4903, 
Col. Parques del Pedregal, Delegación Tlalpan, 
C.P. 14010, México, D.F. | Tel. 5004.5000 

www.conabio.gob.mx | www.biodiversidad.gob.mx 
Facebook | Twitter | YouTube
