### ISSUE TITLE
Definir nombres para vistas y búsquedas

### ISSUE THREAD

**Issue by albertoglezba** [calonso-conabio/buscador#36]
Hay confusión para más de la mitad del equipo de desarrollo (y potencialmente para el universo de usuarios) al referirse a las vistas básica/avanzada y búsquedas básica/avanzada (4 búsquedas en total, 2 vistas con 2 búsquedas cada una dichas búsquedas iguales en el código pero con outputs distintos)

**Comment by calonso-conabio** [comment]
Estoy completamente de acuerdo, se lo preguntare a diana

**Comment by calonso-conabio** [comment]
Al final quedaro vista general y vista de especialistas, busqueda basica y avanzada (solo para la vista de especialistas)

**Comment by albertoglezba** [comment]
Falta unir las busquedas en la vista general, supongo haré eso al ratón

2015-05-22 10:01 GMT-05:00 Carlos Alonso <notifications@github.com>:

> Al final quedaro vista general y vista de especialistas, busqueda basica y
> avanzada (solo para la vista de especialistas)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/calonso-conabio/buscador/issues/36#issuecomment-104682452>
> .
>



-- 


-- Gerardo Alberto González Bautista
-- Saludos!!!

**Comment by calonso-conabio** [comment]
cierto, aunque ya no lo anote porque es mas un cambio de vista que de programacion
