### ISSUE TITLE
Scroll descompone resultados

### ISSUE THREAD

**Issue by albertoglezba** [calonso-conabio/buscador#37]
En esta ruta:

/especies/resultados?utf8=%E2%9C%93&id=&busqueda=nombre_cientifico&por_pagina=50&estatus%5B%5D=2&nombre_cientifico=o&button=

En ambas vistas, al activarse el evento de scroll para traer maás resultados, desaparecen los filtros y el siguiente set de resultados aparece movido a la derecha, mi sospecha es... ninguna

**Comment by calonso-conabio** [comment]
No habia visto el bug, me imagino que es cuando asigno variables para un solo scrolling, pero lo checo.

**Comment by calonso-conabio** [comment]
El resultado de la busqueda basica basica (nombre comun y cientifico) no mandaba al parcial __resultados.html.erb, la solucion fue parecida a la vista avanzada
