### ISSUE TITLE
retroalimentacion

### ISSUE THREAD

**Issue by calonso-conabio** [calonso-conabio/buscador#45]
Que la gente pueda enviar comentarios, sugerencias o cambios a nivel de especie (sin necesidad de registrarse), se tendria que crear una tabla de "comentarios" y otra de "especie_comentarios"

**Comment by albertoglezba** [comment]
No se requiere una tabla intermedia, ya que es una tabla uno a muchos, pueden coexistir los 3 campos en la misma tabla comentarios

**Comment by calonso-conabio** [comment]
cierto, cierto!

**Comment by calonso-conabio** [comment]
El envio de comentarios ya se guarda en la base, sin embargo queda pendiente un modulo de administracion de estos mismos
