### ISSUE TITLE
Cambios en la pantalla de inicio

### ISSUE THREAD

**Issue by albertoglezba** [calonso-conabio/buscador#46]
Si es la primera vez visitándonos, preguntar al usuario que vista quiere (general o de especialistas) y en el index de especies, donde están las imágenes, poner justo un random de fotos del banco de imágenes,  se sugiere un random entre 1000000 y 10000000 que tenga foto del banco de iis para que pedirlas redimensionadas, etc etc etc.

Adicionalmente, se podría dar preferencia (o restarle) a las especies mas visitadas: https://github.com/calonso-conabio/buscador/issues/30

**Comment by calonso-conabio** [comment]
Lo de mostrar fotos random es buena idea pero no de toda la base, ya que existen fotos deberas muy malas y le van a quitar vista, podriamos decirle a Carlos o Laura Cardenas que nos propongan una carpeta de imagenes especiales para el inicio

**Comment by albertoglezba** [comment]
Bueno, en lo que proponen, pueden utilizarse las más visitadas ;)

**Comment by albertoglezba** [comment]
Además unicamente se requiere la ruta, no que las copiena  otra carpeta distinta y shalala
