### ISSUE TITLE
error en las búsquedas vista avanzada, (indecidible)

### ISSUE THREAD

**Issue by albertoglezba** [calonso-conabio/buscador#49]
Cuando estás en la vista de especialistas, en la búsqueda avanzada, el nombre común no te despliega el menú de  inferior a..., aunado a ellos, si se escribe algo en el nombre científico, y luego se selecciona algo (via redis) en el nombre común, se realiza la búsqueda por nombre científico SIEMPRE, es confuso al usuario.

(EJEMPLO, buscar grillos en ambas casetas sin limpiar la búsqueda, en uno seleccionar grillos y en otro grimiales)

**Comment by calonso-conabio** [comment]
Si este ya lo habia visto, uno tiene que tener precedencia asi que dejare el ultimo que autocomplete, y si solo busca por nombre cientifico que taambien te despliegue la categoria taxonomica

**Comment by calonso-conabio** [comment]
La caseta de nombre comun ya despliega las categorias taxonomicas, y si seleccionas ambas te deja la ultima seleccion.
